### ISSUE TITLE
switching to non max. window on new workspace

### ISSUE THREAD

**Issue by holger-bauer** [rockon999/dynamic-panel-transparency#1]
Hi.

panel is not darkened correctly when I do the following

1. open two windows on a workspace, one maximized, one not
2. focus non-ma. windows
3. go to another workspace with no window or non max window focused
4. go back to previous workspace
5. switch to max window

Panel will still be transparent and not opaque.
I do use Fedora 23 and GNOME 3.18.1

**Comment by rockon999** [comment]
Hi! The latest git should fix this bug. If you could test it that'd be great!

**Comment by holger-bauer** [comment]
I've tested with git version and it's fixed. Thanks!
