### ISSUE TITLE
[3.34] Cant open app chooser

### ISSUE THREAD

**Issue by jedrzejowski** [rockon999/dynamic-panel-transparency#103]
When i'm trying to open app chooser in preference i got following error(window doesn't open ofc):
```
JS ERROR: TypeError: ExtensionUtils.extensions is undefined
_init@/home/adam/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/prefs.js/preferences/appChooser.js:69:1
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
buildPrefsWidget/<@/home/adam/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/prefs.js/preferences/main.js:683:22
main@resource:///org/gnome/shell/extensionPrefs/main.js:707:5
```
I tried for searching for this error and found this:
https://stackoverflow.com/questions/58085645/gnome-shell-3-34-missing-extensionutils-extension-property

**Comment by rockon999** [comment]
This is fixed now in the `master` branch. I'll publish the fix to GNOME Extensions soon.

**Comment by jedrzejowski** [comment]
Yes, i tried the repo version, and it worked
