### ISSUE TITLE
Does not work with ZukiShell shell theme

### ISSUE THREAD

**Issue by isness** [rockon999/dynamic-panel-transparency#12]
When there are no maximized windows, the panel seems to be half-transparent, that is, the lower part of it is opaque, while the upper is transparent. As if some kind of gradient is applied. When I maximize a window, however, it fades to black as it should. 

Screenshot: http://ipix.lt/image/V6uO

OS: Ubuntu Gnome 15.04 64-bit

**Comment by rockon999** [comment]
ZukiShell seems to be using a panel property that this extension doesn't currently block. My weekend is currently quite hectic, so it may take me a day or two to release a fix on the GitHub. It'll probably be on the official Gnome Extensions by the end of the week!

**Comment by isness** [comment]
Thank you for the quick reply. It's really not urgent at all, take all the time you need :)

**Comment by rockon999** [comment]
The next release should include support for this. My February got a little busier than I thought! I estimate a week before release. :)

**Comment by isness** [comment]
Thanks!
