### ISSUE TITLE
Dropdown terminal doesn't make the bar black

### ISSUE THREAD

**Issue by tengwar** [rockon999/dynamic-panel-transparency#13]
It's really weird to use this extension with https://extensions.gnome.org/extension/442/drop-down-terminal/ because there's a transparent bar over the dark terminal. For example of a "transparent panel" extension that works with dropdown terminal see https://github.com/AMDG2/GnomeShell_DynamicTopBar .

**Comment by rockon999** [comment]
Hi! Support for drop down terminals is currently in the development branch. It will be integrated into the main release soon!

**Comment by rockon999** [comment]
The development branch changes have been merged into the master branch, so if you wish to test out the new features you may. This was a huge upgrade for the plugin, so it is possible there may still be some bugs. Thanks!

**Comment by tengwar** [comment]
This bug seems fixed but now the terminal's dropping down seems slower, like it's waiting for the panel transition to finish. How to reproduce: set the transition speed to a high value (like 1500 ms), go to a new, empty workspace, _wait until panel is 100% transparent_ and engage the terminal. It seems like this isn't 100% deterministic though.

**Comment by rockon999** [comment]
Hi! I'm unable to test this extension as my Linux machine is currently a HiDPI setup and the extension is rather buggy on HiDPI (https://github.com/zzrough/gs-extensions-drop-down-terminal/issues/124). I can't think of a great way to fix this besides using an application such as (Guake) or using a lesser transition speed. You could try enabling 'force animation' in settings, this allows the extension to bypass many Gnome controls on animations.
