### ISSUE TITLE
Text not readable on clear background

### ISSUE THREAD

**Issue by Dremor** [rockon999/dynamic-panel-transparency#15]
Top bar text is difficult to read when using a clear background (for example GNOME default background).

A good way to do it is to add a shadow behind the letters (see this extension for an example : https://github.com/AMDG2/GnomeShell_DynamicTopBar)

**Comment by rockon999** [comment]
This feature will be added in the next release.

**Comment by Dremor** [comment]
Thank you ;)

**Comment by Dremor** [comment]
Just tested with the new shadowing. Look good, except that the gray text don't contrast enough with the shadow, making it difficult to read on some wallpapers (especially gray ones).

The other addon made the text whit to avoid this problem.

**Comment by rockon999** [comment]
I'll consider adding text coloring. Right now it relies on whatever theme you have in place to color and style the text.

**Comment by rockon999** [comment]
I've decided that for now all text will be white when shadowing is enabled to combat this issue. I've been unable to find a good solution to add customizable text color, and until then I think this will satisfy most use cases.
