### ISSUE TITLE
Error when opening the settings

### ISSUE THREAD

**Issue by davidpapadie** [rockon999/dynamic-panel-transparency#17]
I get the following when trying to open the settings for the extension in gnome tweak tool using gnome 3.16.4:

![screenshot from 2016-03-03 22-52-29](https://cloud.githubusercontent.com/assets/17624202/13509148/b796ab78-e192-11e5-8eb4-1c02c4209c6e.png)

TypeError: theme_overlay.reorder_overlay is not a function

Stack trace:
  getPrefsWidget@/home/stefan/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/prefs.js:136
  buildPrefsWidget@/home/stefan/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/prefs.js:51
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:95
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:259
  wrapper@resource:///org/gnome/gjs/modules/lang.js:169
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397
  @<main>:1

**Comment by rockon999** [comment]
Whoops! Seems I used GUI code only available in 3.18. I'll see if I can find another way to do this.

**Comment by rockon999** [comment]
The latest development branch should fully fix this bug.

**Comment by davidpapadie** [comment]
Nice work, now I can open the settings. Do you know why do the tabs on Gnome's top bar have a dark "v" appended to the right, just after the rightmost character. Even the tab with the buttons for shutdown volume, and network connection has it.

**Comment by rockon999** [comment]
I'm not sure what you mean by 'tabs' but it's probably text shadowing. You can disable it in settings.

**Comment by rockon999** [comment]
I'm guessing by 'tabs' you meant the drop down arrows? I've noticed a bug in their shadowing and it will be fixed in the next push.
