### ISSUE TITLE
Not working properly on fresh Ubuntu 16.04 install

### ISSUE THREAD

**Issue by 9Morello** [rockon999/dynamic-panel-transparency#23]
I can install the extension and get a transparent top bar after reseting the shell with alt+f2 --> r. However, after maximizing a window, I cannot make the top bar transparent anymore, not even by closing everything. It only gets transparent again if I restart the shell one more time.

Fresh install of Ubuntu 16.04.

Edit: just posting more details.
I'm using GNOME 3.18.4, and I also have the following extensions enabled: Alternatetab, Applications menu and Places status indicator. I tried installing the latest version and it didn't work, this time not getting transparent even after reseting the shell. Its the same with it on and off. Changing the panel color works normally. I can make it transparent all the time by changing the maximum transparency value and reseting the shell.

**Comment by rockon999** [comment]
Do you have animations disabled?

**Comment by 9Morello** [comment]
Yes, they are enabled. I'm sorry, how do I try ¨force animation¨?

I'm not using any themes.

**Comment by rockon999** [comment]
It is in the preferences. You'll need Gnome Tweak Tool.

**Comment by 9Morello** [comment]
I'm sorry, I didn't find any "force animation" option in Gnome Tweak Tool. Are you refereeing to this?

https://fuwa.se/f/0GUQ_D.png

**Comment by rockon999** [comment]
You go to Extensions > Dynamic Panel Transparency > Force Animation

**Comment by 9Morello** [comment]
Just checked it, its enabled.

**Comment by rockon999** [comment]
Did it fix anything? If you could also send me logs that would be great. After restarting the shell enter **journalctl --since "20 seconds ago"** in terminal. That will give you any errors from the extension.

**Comment by 9Morello** [comment]
It was enabled before.
Here is the log: http://pastebin.com/A7c1Z2Z6

**Comment by rockon999** [comment]
There doesn't seem to be any indication that the extension is failing. I suggest you disable your other extensions and see if it works without them. I'll keep thinking about what could be going wrong in your case though.

**Comment by 9Morello** [comment]
I've tested it without any other extension too, still not working.
Thanks for your attention, I'll wait for it. Looks really good.

**Comment by rockon999** [comment]
@9Morello Do you have desktop items enabled?

**Comment by 9Morello** [comment]
Yes, I do.
I just tested with it disabled and it worked!

**Comment by rockon999** [comment]
Okay! I've released a patch that fixes this issue. It's pending review on Gnome Extensions, but is available now on the GitHub. Thanks!

**Comment by rockon999** [comment]
Fixed in v9. Closed.
