### ISSUE TITLE
Change text color to fit the background color

### ISSUE THREAD

**Issue by alexmigf** [rockon999/dynamic-panel-transparency#26]
I use a background with top color more white, and with the white text on the top bar doesn't fit well. Elementary OS for example does this interpretation and changes the color of the text so can be readable.

Nice extension by the way.

**Comment by rockon999** [comment]
I attempted implementing this in the past and encountered some difficulties finding a good way to dynamically change the color of the text itself. I'll definitely consider this again, but for now I'd recommend using 'Add Text Shadow' or, if you really wish to change the text color, switching to a more appropriate Gnome Shell theme.

**Comment by rockon999** [comment]
Thanks!

**Comment by DoctorJellyface** [comment]
Can we just have an option to set the colour of the text on transparent background (defaulted to white)? I mean we don't really need more options, the colour on the solid background is handled quite well.

**Comment by rockon999** [comment]
It isn't that I don't want to implement this feature. This issue is how to do it. Right now to produce the white I use a theming file; I haven't figured out how to apply the color in the actual extension without using predefined theming files. I'm considering just having a dark/light option to make the text more visible. That would be doable.

**Comment by alexmigf** [comment]
Yes, should be enough :)

**Comment by DoctorJellyface** [comment]
You can also look at how the other dynamic top bar extension does it.

**Comment by rockon999** [comment]
It doesn't have text coloring... I'm fairly certain of that.

**Comment by rockon999** [comment]
I've hacked full text coloring into the extension. It will be included in v10 or v11. Thanks for the suggestions!

**Comment by rockon999** [comment]
Update: v11 is set to be released in the upcoming weeks with this feature. I've entered final bug testing and am establishing compatibility with shell versions 3.14-3.20.

**Comment by rockon999** [comment]
v11 is now in the master branch. This is a major rewrite so some bugs may occur. If you have any time to test the new version I'd very much appreciate it!

Thanks!

**Comment by rockon999** [comment]
Feature added in v11 (which was just released!).
