### ISSUE TITLE
Suggestion: let us configure the text shadow

### ISSUE THREAD

**Issue by 9Morello** [rockon999/dynamic-panel-transparency#27]
I think this will be a nice option for those, like me, wanting something similar Elementary OS's Wingpanel. I think the shadows are just a bit too big, and it would be nice to configure them.

Picture, for reference: https://i.imgur.com/w9mMwc9.png

**Comment by rockon999** [comment]
Hi! I'm working on this feature along with colored text. There are some roadblocks preventing this, but I think I've recently found a way around them. I hope to include this in either v10 or v11. Thanks!

**Comment by rockon999** [comment]
Update: v11 is set to be released in the upcoming weeks with this feature. I've entered final bug testing and am establishing compatibility with shell versions 3.14-3.20.

**Comment by 9Morello** [comment]
Good work! Nice to hear that.

**Comment by rockon999** [comment]
v11 is now in the master branch. This is a major rewrite so some bugs may occur. If you have any time to test the new version I'd very much appreciate it!

Thanks!

**Comment by 9Morello** [comment]
I'm not using a computer with GNOME installed right now, but I'll try it as soon as I get my hands in one.

**Comment by rockon999** [comment]
There is also an icon shadow setting added. It will work on _most_ panel icons.

**Comment by rockon999** [comment]
v11 is officially released!
