### ISSUE TITLE
Conflicts with Activities Configurator

### ISSUE THREAD

**Issue by jestrella04** [rockon999/dynamic-panel-transparency#28]
When this extension is used together with "Activities Configurator" panel transparency is never set. The latter does have a similar feature but even tho it is disabled they don't play well together.

https://extensions.gnome.org/extension/358/activities-configurator/

**Comment by rockon999** [comment]
Hello! I will work on testing this issue. I'm currently unable to work on this as I'm competing in national debate competitions, but I'll be back at work in a approx. a week. I'll do my best to resolve this if I have time but I can't promise anything.

P.S. It is possible I can't resolve this. Extensions that significantly change the panel may make it impossible for my extension to coexist.

**Comment by rockon999** [comment]
Make sure you're not setting the 'Panel Background', 'Override Shell Theme' is off, and 'Window Maximized Effect' is set to 'Panel - No Effect'. With those settings my installation seems to coexist perfectly. Let me know if the issue persists and I'll see what I can do.
