### ISSUE TITLE
InternalError: too much recursion

### ISSUE THREAD

**Issue by Saend** [rockon999/dynamic-panel-transparency#29]
The extension was installed from extensions.gnome.org which shows a red "error" label after reloading the page. The looking glass prints `InternalError: too much recursion`

The extension behaves normally with one exception: when unmaximizing a window the panel stays dark, you need to open the overview to reset the opacity.

To be precise :

1. Maximize a window -> panel gets dark
2. Unmaximize the window -> panel stays dark
3. Open overview -> panel gets transparent
4. Close overview -> panel stays transparent

Other case:

1. Maximize a window -> panel gets dark
2. Open overview -> panel gets transparent
3. Close overview -> panel gets dark
4. Unmaximize the window -> panel stays dark

Disabling every other extension doesn't fix the issue.
Gnome version 3.20.2 running up to date ArchLinux.

**Comment by rockon999** [comment]
Hello! I will work on testing this issue. I'm currently unable to work on this as I'm competing in national debate competitions, but I'll be back at work in a approx. a week. I'll do my best to resolve this if I have time but I can't promise anything.

**Comment by rockon999** [comment]
One more thing... are you using release or development?

**Comment by rockon999** [comment]
I'm unsure where this issue is occurring. I cannot reproduce. Try disabling every extension and restarting your shell afterward; an extension could be not disabling properly. I definitely need to know what your settings are in addition to the full error log.

**Comment by Saend** [comment]
I tried it again today with the master branch from github, without any other extensions enabled, after restarting gnome. Same (and only) error in looking glass.

I did find this in journalctl :
```
org.gnome.Shell.desktop[25594]: Gjs-Message: JS LOG: Extension "dynamic-panel-transparency@rockon999.github.io" had error: InternalError: too much recursion
org.gnome.Shell.desktop[25594]: (gnome-shell:25594): Gjs-WARNING **: JS ERROR: InternalError: too much recursion
org.gnome.Shell.desktop[25594]: get_background_alpha@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/theming.js:110
org.gnome.Shell.desktop[25594]: set_corner_color@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/theming.js:52
org.gnome.Shell.desktop[25594]: hide_corners@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/transitions.js:215
org.gnome.Shell.desktop[25594]: fade_out@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/transitions.js:115
org.gnome.Shell.desktop[25594]: fade_out@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/transitions.js:121
org.gnome.Shell.desktop[25594]: fade_out@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/transitions.js:121
org.gnome.Shell.desktop[25594]: fade_out@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/transitions.js:121
org.gnome.Shell.desktop[25594]: fade_out@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/transitions.js:121
org.gnome.Shell.desktop[25594]: fade_out@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/transitions.js:121
org.gnome.Shell.desktop[25594]: fade_out@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/transitions.js:121
org.gnome.Shell.desktop[25594]: fade_out@/home/saend/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/transitions.js:121
... [10 more pages of the same line]
```

What other log can I provide? What kind of settings do you need to know?

**Comment by rockon999** [comment]
I found the bug! It seems there was an issue in the code that is only invoked on very rare occasions. I've corrected this and the latest master should fix your issue.

**Comment by Saend** [comment]
That fixed it, thanks! 
I love the extension btw.

**Comment by rockon999** [comment]
Thanks! The bug fixes will be up on Gnome Extensions in a few days.
