### ISSUE TITLE
Override border-image

### ISSUE THREAD

**Issue by zagortenay333** [rockon999/dynamic-panel-transparency#3]
Some themes use the `border-image` property so this won't work.

**Comment by rockon999** [comment]
Hi! Can you please provide an example?

**Comment by zagortenay333** [comment]
You mean an example of a theme? My ciliora themes use images: https://github.com/zagortenay333/ciliora-tertia-shell

**Comment by rockon999** [comment]
This extension now overrides border-image and related panel settings.

**Comment by zagortenay333** [comment]
Thx
