### ISSUE TITLE
Regression in Drop Down Terminal Compatibility

### ISSUE THREAD

**Issue by xtor91** [rockon999/dynamic-panel-transparency#30]
The latest update (v9) broke the previous compatibility with [Drop Down Terminal](https://github.com/zzrough/gs-extensions-drop-down-terminal); the panel doesn't become visible when the terminal is opened.

Tested in GNOME 3.20.3 and Drop Down Terminal v20.

**Comment by rockon999** [comment]
The code that broke 'Drop Down Terminal' was needed to make desktop icons workable in 3.20. I'll do my best to modify the relevant code to allow for 'Drop Down Terminal' again.

**Comment by rockon999** [comment]
** I cannot currently test this work as 'Drop Down Terminal' is broken on HiDPI setups.

**Comment by rockon999** [comment]
The latest commit should fix your issue.

**Comment by xtor91** [comment]
Thanks for the quick reply, @rockon999. I can confirm that the commit fixes the issue.

Closing this bug.
