### ISSUE TITLE
Theme detection from the panel is broken.

### ISSUE THREAD

**Issue by thomasstevenson** [rockon999/dynamic-panel-transparency#31]
Firstly, thanks for making such a cool Extension!

Unfortunately, I've noticed a problem when using some Gnome Shell themes that don't have a black panel background, such as the OS X El Capitan theme: https://www.gnome-look.org/p/1013490/
Even though I've enabled the "Detect User Theme" setting and selected to use the Panel as the source, the panel always has a black background (with the appropriate opacity, of course) and white text. It doesn't seem to use the Gnome Shell theme's background and text colors, it just overwrites them.

Here's how the panel looks with the Dynamic Panel Transparency extension disabled (how the theme sets the panel color):
![screenshot from 2016-07-14 01-27-26](https://cloud.githubusercontent.com/assets/7741618/16824762/4d108422-4966-11e6-8e4c-a231a5e87018.png)

And this is the with the Dynamic Panel Transparency extension enabled (with the panel background and text colors overwritten):
![screenshot from 2016-07-14 01-27-38](https://cloud.githubusercontent.com/assets/7741618/16824767/57f49ea0-4966-11e6-94e1-244774e7a208.png)

Would it be possible to simply make the theme's panel background color more transparent instead of overwriting its colors for the next version of the extension?

**Comment by rockon999** [comment]
The trouble is that I simply can't avoid overwriting the panel's colors. The 'normal' way of altering the panel's transparency is to use stylesheets. I, however, bypass the stylesheets in order to add proper transitions. By doing this I overwrite all theme colors. The price you pay for the better visual effect is less compatibility with Gnome themes. I can, however, work to improve theme detection. I'll experiment with the El Capitan theme and see what I can do.

**Comment by rockon999** [comment]
**You can also set your own background to match your preferred theme.

**Comment by thomasstevenson** [comment]
Thanks for replying so quick! If the theme detection can be improved so that the overwritten background color could match that of the theme's original background color (with the set transparency, of course), that would be the prefect solution.

Once again, thanks for making this extension. It's one of the best ones out for Gnome!

**Comment by rockon999** [comment]
Update: I've decided to remove theme detection from v11 as I couldn't find a way to make it work properly. Instead, users will just have to pick their own background color in preferences.

**Comment by rockon999** [comment]
In a surprising plot twist I figured out how to implement theme detection... so v11 has an updated and completely working version! Also, v11 is now in the master branch! This is a major rewrite so some bugs may occur. If you have any time to test the new version I'd very much appreciate it!

Thanks!

**Comment by rockon999** [comment]
v11 is officially released. This feature has been fixed!
