### ISSUE TITLE
Transparency isn't updated when keyboard shortcuts are used.

### ISSUE THREAD

**Issue by GitHaarek** [rockon999/dynamic-panel-transparency#32]
If you have open a maximized window and use the shortcut Super+D or Ctrl+Super+D, to hide the window, the transparency is never set.

**Comment by rockon999** [comment]
What Gnome and extension versions are you running?

**Comment by rockon999** [comment]
I can reproduce. I'll work on getting that fixed. Should be released with other recent bug fixes soon.

**Comment by GitHaarek** [comment]
I did not expect a reply as quickly as this, but great and thank you very much! The extension is very much appreciated.

**Comment by rockon999** [comment]
This issue is fixed in the newest development version. The current system of monitoring window maximization has been completely overhauled and will now function much better! You can expect to see the changes once I've stabilized the development branch and merge it in. (Probably v11 or v12)

**Comment by GitHaarek** [comment]
That's fantastic! I appreciate you. :)

**Comment by rockon999** [comment]
Update: v11 is set to be released in the upcoming weeks. I've entered final bug testing and am establishing compatibility with shell versions 3.14-3.20.

**Comment by rockon999** [comment]
v11 is now in the master branch. This is a major rewrite so some bugs may occur. If you have any time to test the new version I'd very much appreciate it!

Thanks!

**Comment by rockon999** [comment]
v11 is officially released. This bug has been squashed!
