### ISSUE TITLE
Dynamic Panel + Dash to Dock

### ISSUE THREAD

**Issue by ThiagoLopes** [rockon999/dynamic-panel-transparency#4]
Hi

-There is a problem when you click on a dock icon (Dash to Dock), he still remains transparent.

Gnome 3.18

**Comment by rockon999** [comment]
Hi! I actually have Dash to Dock and can't seem to replicate this. Could you go into more detail about what specifically causes it (certain applications, conditions, etc.)?

**Comment by ThiagoLopes** [comment]
Hi!
Any program that is maximized, clicking in program by Dash to dock do not let the black bar.
![captura de tela de 2015-11-23 14-16-08](https://cloud.githubusercontent.com/assets/5994972/11342128/dda61aa6-91ec-11e5-8d93-f8c6d9823882.png)

**Comment by rockon999** [comment]
Hi! I see the problem now! The next release will fix this. I'm planning to push the latest release within the next few days.

**Comment by ThiagoLopes** [comment]
Thanks! i really appreciate your work

**Comment by rockon999** [comment]
Hi! I've just published the new release in the repo. If you'd like to try it out now that'd be great! It's a huge update and I probably won't release it on Gnome Extensions for a few days. (Have to iron out any bugs)

**Comment by ThiagoLopes** [comment]
Hi, the problem with dash dock is fixed, but now have has a same problem now with activities menu (super key)

**Comment by rockon999** [comment]
Hm. Try running the latest (as of one minute ago). I'm not having issues with it.

**Comment by ThiagoLopes** [comment]
Same problem :/
I will go investigate
I am using Fedora 23

**Comment by ThiagoLopes** [comment]
forget last report, i updated the extension and works!
thanks for the last update! :100:
