### ISSUE TITLE
Transperancy not triggered after exiting dash applications menu

### ISSUE THREAD

**Issue by TrendaFet** [rockon999/dynamic-panel-transparency#40]
Hello,
There is a bug where if you click on the dash application menu then just return to desktop, the transparency of the top panel is not triggered.

In order to trigger it, you have to open a maximized window then close it or minimize it.

This bug occurs with or without the Dash to Dock extension.

System:
Debian Stretch (Testing)
Gnome 3.22
Dynamic Panel Transparency v11
Arc Theme

I attached screenshots showing how to replicate the bug.

![screenshot from 2016-10-02 07-18-48](https://cloud.githubusercontent.com/assets/17427046/19018860/11c9f298-8879-11e6-9129-ab40194947ba.png)

![screenshot from 2016-10-02 07-19-00](https://cloud.githubusercontent.com/assets/17427046/19018865/2bd60456-8879-11e6-9f4c-0597469075fa.png)

![screenshot from 2016-10-02 07-19-06](https://cloud.githubusercontent.com/assets/17427046/19018868/381d77da-8879-11e6-93da-55825945d9e6.png)

Thanks for an awesome extension, keep up the great work.

**Comment by rockon999** [comment]
I can't reproduce on 3.20, so it must be a bug introduced by 3.22. I'll investigate as soon as I can update and/or virtualize. Arch Linux usually has the Gnome update within a few weeks of release.

**Comment by rockon999** [comment]
Also, could you paste the output from `journalctl --since "20 seconds ago"` when this occurs?

**Comment by TrendaFet** [comment]
Sure.

```
-- Logs begin at Sun 2016-10-02 07:41:45 EET, end at Sun 2016-10-02 20:38:16 EET. --
Oct 02 20:38:16 dell sudo[31555]:      trendafet : TTY=pts/0 ; PWD=/home/trendafet ; USER=root ; COMMAND=/bin/journalctl --since 20 seconds ago
Oct 02 20:38:16 dell sudo[31555]: pam_unix(sudo:session): session opened for user root by (uid=0)
lines 1-3/3 (END)
```
I completely understand, there is no rush at all. If there is any more information I can provide, please let me know.

**Comment by rockon999** [comment]
I've installed Debian Stretch and I can't seem to replicate your issue. Do you have any other extensions installed? Also, could you send me a picture of this dconf path: org.gnome.shell.extensions.dynamic-panel-transparency?

**Comment by TrendaFet** [comment]
Terribly sorry about my late response.

I've done some tests and was able to track down the conditions to cause this bug. It seems that if Arc theme was chosen as a shell theme (top bar), the bug occurs. If it remains default, all is normal. This is enabled through the preloaded extension "User Themes"

Here is the screenshot you requested:

![screenshot from 2016-10-04 10-02-14](https://cloud.githubusercontent.com/assets/17427046/19066597/b3cf70e0-8a22-11e6-815c-798f1dcdb24c.png)

I'm not entirely sure if this is a bug with the extension or the Arc theme, I would test but I don't have any other themes installed.

As soon as I finish work, I'll grab the latest version of the Arc theme and install another theme to test and let you know.

Thanks again for all the support.

**Comment by TrendaFet** [comment]
I installed the latest Arc theme and recorded a screencast showing the bug in action. Only happens with the Arc theme.

http://imgur.com/6CE1RPA

**Comment by rockon999** [comment]
I can replicate. Some themes are slightly incompatible with the way I add the effect. I can probably fix this issue, but for now go into 'Background' and select 'Remove excess panel styling.' That will fix the issue temporarily.

**Comment by TrendaFet** [comment]
That does indeed work, thank you very much.

**Comment by rockon999** [comment]
The latest version in the GitHub should fix your issues and also improve the theme detection for themes like Arc. I'll push it to Gnome Extensions soon, but in the mean time if you could test it out that'd be great! Thanks!

**Comment by TrendaFet** [comment]
I downloaded and tested, it works perfectly. Full screen then windowed, maximized then windowed and dash applications menu then desktop all work just fine.

Thank you for the fix and fast response, much appreciated.

**Comment by rockon999** [comment]
v13 will be submitted for review on Gnome Extensions tomorrow. This release includes improved theme detection and several tweaks to allow for more general theme compatibility. (Also a Chinese translation if that benefits you in anyway!)

**Comment by TrendaFet** [comment]
That is great news. Thank you for all the work in creating and maintaining this extension.
