### ISSUE TITLE
settings are inverse with 3.22

### ISSUE THREAD

**Issue by rickysarraf** [rockon999/dynamic-panel-transparency#41]
![image](https://cloud.githubusercontent.com/assets/65480/19215115/b30b4268-8db2-11e6-815a-f76c166dacca.png)

Hello,

With shell and plugin version 3.22, I have ended up with the inverse situation. The screenshot has the details of what I'm seeing on my desktop. In it you can see that the extension is off, and the effects are on.

**Comment by rickysarraf** [comment]
Is there someway to debug this, so that I can provide you more information ?

**Comment by rockon999** [comment]
Could you please provide a list of installed extensions and provide the output of `journalctl --since 30 seconds` when enabling and disabling.

**Comment by rockon999** [comment]
The latest version on the GitHub should fix your issue.

**Comment by rickysarraf** [comment]
The problem still exists as is.

Here's the log I could gather.

```
-- Logs begin at Wed 2015-12-02 22:53:58 IST. --
Oct 09 15:18:32 learner gnome-shell[7565]: JS LOG: [Dynamic Panel Transparency] Detected user theme style: rgba(0, 0, 0, 255)
Oct 09 15:18:32 learner gnome-shell[7565]: JS LOG: Activities Configurator Enabled
Oct 09 15:18:32 learner gnome-shell[7565]: GNOME Shell started at Sun Oct 09 2016 15:18:30 GMT+0530 (IST)
Oct 09 15:18:46 learner gnome-shell[7565]: JS LOG: loading default theme (Adwaita)
Oct 09 15:18:47 learner org.gnome.Shell.desktop[7565]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0xa00007 (Onboard).
Oct 09 15:18:48 learner gnome-shell[7565]: JS LOG: Activities Configurator Enabled
Oct 09 15:18:54 learner gnome-shell[7565]: JS LOG: [Dynamic Panel Transparency] No background image found in user theme.
Oct 09 15:18:54 learner gnome-shell[7565]: JS LOG: [Dynamic Panel Transparency] No border image found in user theme.
Oct 09 15:18:54 learner gnome-shell[7565]: JS LOG: [Dynamic Panel Transparency] Detected user theme style: rgba(0, 0, 0, 128)
Oct 09 15:19:15 learner evolution[8077]: void webkit_uri_scheme_request_finish(WebKitURISchemeRequest*, GInputStream*, gint64, const gchar*): assertion 'G_IS_INPUT_STREAM(inputStream)' failed
Oct 09 15:19:55 learner gnome-shell[7565]: JS LOG: [Dynamic Panel Transparency] No background image found in user theme.
Oct 09 15:19:55 learner gnome-shell[7565]: JS LOG: [Dynamic Panel Transparency] No border image found in user theme.
Oct 09 15:19:55 learner gnome-shell[7565]: JS LOG: [Dynamic Panel Transparency] Detected user theme style: rgba(0, 0, 0, 128)
Oct 09 15:20:10 learner gnome-shell[7565]: JS LOG: [Dynamic Panel Transparency] No background image found in user theme.
Oct 09 15:20:10 learner gnome-shell[7565]: JS LOG: [Dynamic Panel Transparency] No border image found in user theme.
Oct 09 15:20:10 learner gnome-shell[7565]: JS LOG: [Dynamic Panel Transparency] Detected user theme style: rgba(0, 0, 0, 128)

```

**Comment by rockon999** [comment]
I think I know what is occurring. Are you disabling it right after a shell restart and/or enabling the extension?

**Comment by rockon999** [comment]
Okay the *latest* GitHub will hopefully fix this bug.

**Comment by rickysarraf** [comment]
I see the last commit from 10 hrs ago. Did you miss to push your changes ?

**Comment by rockon999** [comment]
Whoops. Sorry about that. The push failed.

**Comment by rickysarraf** [comment]
That hasn't helped either. To cut out any confusion, I logged out and logged back in. I still have the inverse effect. :-(


```
Oct 09 21:02:42 learner parcimonie-applet.desktop[17507]: Cannot reach the daemon's D-Bus service. Let' wait 4 seconds before retrying. at /usr/share/perl5/App/Parcimonie/Applet.pm line 205.
Oct 09 21:02:42 learner org.gnome.Shell.desktop[17451]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0xc00007 (Onboard).
Oct 09 21:02:42 learner org.gnome.Shell.desktop[17451]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0xc00007 (Onboard).
Oct 09 21:02:42 learner onboard[17495]: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Oct 09 21:02:43 learner org.gnome.Shell.desktop[17451]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0xc00007 (Onboard).
Oct 09 21:02:43 learner gnome-shell[17451]: JS LOG: [Dynamic Panel Transparency] No background image found in user theme.
Oct 09 21:02:43 learner gnome-shell[17451]: JS LOG: [Dynamic Panel Transparency] No border image found in user theme.
Oct 09 21:02:43 learner gnome-shell[17451]: JS LOG: [Dynamic Panel Transparency] Detected user theme style: rgba(0, 0, 0, 128)
Oct 09 21:02:43 learner gnome-shell[17451]: GNOME Shell started at Sun Oct 09 2016 21:02:39 GMT+0530 (IST)
Oct 09 21:02:44 learner onboard[17495]: AT-SPI: Error in GetItems, sender=(null), error=Did not receive a reply. Possible causes include: the remote application did not send a reply, the mess
Oct 09 21:02:46 learner parcimonie-applet.desktop[17507]: Cannot reach the daemon's D-Bus service. Let' wait 9 seconds before retrying. at /usr/share/perl5/App/Parcimonie/Applet.pm line 205.
```

**Comment by rickysarraf** [comment]
Why does the log complain that no background image was found ? Especially, when I do have a background image set.

**Comment by rockon999** [comment]
Some shell themes use a background image for the panel, your theme does not. The extension detects if your shell theme is using images so it doesn't conflict with them. I may alter the message to make this more clear.

I don't know what could be causing this inverse effect, but I'll keep looking into it. Nothing in the log indicates an error, so there is probably a logical bug or version incompatibility somewhere. I'll test the extension again on 3.22 when I get the chance to start up my 3.22 virtual machine, as I'm not seeing the issue on 3.20.

Also, what theme are you using?

**Comment by rickysarraf** [comment]
You know, sometimes I wonder, why do I get all the weird issues in the world. :-(

To cut out confusion, I uninstalled your extension, rebooted the machine. And right now, your extension's effects are in-effect.

I do have the desired effect, and that too with one less extension. But I don't like this "magical" way of it working, especially on my machine. Is there any way else I should investigate this ? Any suggestions ?

I looked into the logs, and as expected, I do not see any thing about panel color change.

```
rrs@learner:~$ journalctl _PID=7572
-- Logs begin at Wed 2015-12-02 22:53:58 IST, end at Sun 2016-10-09 22:07:17 IST. --
Sep 12 21:53:02 learner gnome-keyring-ssh.desktop[7572]: SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
-- Reboot --
Oct 09 22:04:39 learner gnome-shell[7572]: JS LOG: Failed to launch ibus-daemon: Failed to execute child process "ibus-daemon" (No such file or directory)
Oct 09 22:04:40 learner gnome-shell[7572]: JS LOG: Failed to add search provider /usr/share/gnome-shell/search-providers/org.gnome.bijiben-search-provider.ini: TypeError: appInfo is null
Oct 09 22:04:41 learner gnome-shell[7572]: JS WARNING: [/home/rrs/.local/share/gnome-shell/extensions/laine@knasher.gmail.com/extension.js 374]: applying the 'delete' operator to an unqualifi
Oct 09 22:04:43 learner gnome-shell[7572]: JS LOG: loading default theme (Adwaita)
Oct 09 22:04:44 learner org.gnome.Shell.desktop[7572]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0xc00007 (Onboard).
Oct 09 22:04:44 learner org.gnome.Shell.desktop[7572]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0xc00007 specified for 0xc0001b (Onboard).
Oct 09 22:04:44 learner org.gnome.Shell.desktop[7572]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0xc00007 (Onboard).
Oct 09 22:04:44 learner gnome-shell[7572]: JS LOG: Activities Configurator Enabled
Oct 09 22:04:45 learner org.gnome.Shell.desktop[7572]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0xc00007 (Onboard).
Oct 09 22:04:45 learner org.gnome.Shell.desktop[7572]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x0 specified for 0xc00007 (Onboard).
Oct 09 22:04:46 learner gnome-shell[7572]: GNOME Shell started at Sun Oct 09 2016 22:04:40 GMT+0530 (IST)
Oct 09 22:04:57 learner gnome-shell[7572]: Allocating size to ShellEmbeddedWindow 0x3a14960 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocat
Oct 09 22:04:57 learner gnome-shell[7572]: Allocating size to ShellEmbeddedWindow 0x3a14960 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocat
```

**Comment by rickysarraf** [comment]
Regarding the theme, my GNOME setup is pretty stock.

![image](https://cloud.githubusercontent.com/assets/65480/19222068/81c1a7e0-8e6d-11e6-9f96-c18cb3048bc5.png)

And this one is where it shows that your extension has been removed, and I still have the desired effect.

![image](https://cloud.githubusercontent.com/assets/65480/19222071/9adf89b8-8e6d-11e6-8b42-a9dcadef2a36.png)

**Comment by rockon999** [comment]
Wait. You have Activities Configurator installed. Activities Configurator replicates some of the functionality of my extension. The effect you're seeing if probably Activities Configurator, not mine. Try going into AC's preferences and under 'Window Maximization' select 'No Effect'.

If that doesn't solve this, I find this very odd. I booted up a clean virtual machine of Debian Testing (3.22) and I can't reproduce. On my virtual machine I can disable, enable, remove all without any issue. Can you look and see in /.local/share/gnome-shell/extensions/ and see if my extension in still in the folder?

**Comment by rickysarraf** [comment]
Thank you very much for being so patient in working with me on this bug (of my own). After removing "Activities Configurator" extension, I can get my desired effect.

This is why I keep a test user a/c so that I can test well before concluding a bug. BTW, do you recent commits, that you made while helping me out, still apply ? Or will those be reverted.

**Comment by rockon999** [comment]
The recent commits fix bugs that I had missed earlier. They are rare and are very unlikely to occur, but they'll still be helpful.
