### ISSUE TITLE
Session crash when extension is enabled. [3.18, 3.20, 3.22]

### ISSUE THREAD

**Issue by dsreyes1014** [rockon999/dynamic-panel-transparency#42]
This extensions just crashes the whole session.  Really like this extension but it just crashes after latest update.

**Comment by nikolowry** [comment]
Same - I had it installed via extensions.gnome.org. I don't know the pervious version I had installed, but I don't recall any problems on 3.22

**Comment by henriquemelissopoulos** [comment]
same for me!

**Comment by CircuitCoder** [comment]
Same here. Using gnome 3.18 on Ubuntu 16.04 from the official APT repo (3.18.5-0ubuntu0.1).

**Comment by rockon999** [comment]
So sorry to here this! Could you please past the relevant information from `journalctl --since "# seconds ago` replacing the `#` with the number of seconds since this occurred. Also a screenshot of any extensions you have installed would be very helpful!

**Comment by rockon999** [comment]
I've suspended the latest update so no more people should be affected. If any of you remember the last update you were on before this issue it'd be very helpful in determining the exact issue (along with the logs from above).

**Comment by CircuitCoder** [comment]
I've just reinstalled the plugin through github, and the journalctl output is here. Ignore errors caused by `dynamic-panel-transparency-master`, it's just an empty folder.

[log.txt](https://github.com/rockon999/dynamic-panel-transparency/files/531035/log.txt)

Other extensions installed:
- Dash to Dock
- Lock keys
- Media player indicator
- Proxy switcher
- Removable drive menu
- Status title bar
- Topicons plus
- User themes

**Comment by rockon999** [comment]
I don't see anything in the log that would cause a session crash. Could you delete the `dynamic-panel-transparency-master` folder just to make sure that isn't causing issues?

**Comment by rockon999** [comment]
Wait I may have found the issue.

**Comment by rockon999** [comment]
Try the latest commit.

**Comment by CircuitCoder** [comment]
Unfortunately, the crash still occurs. This time I've disabled all other extensions.
[log2.txt](https://github.com/rockon999/dynamic-panel-transparency/files/531572/log2.txt)

**Comment by rockon999** [comment]
The latest commit will hopefully fix this issue. The issue is essentially that Ubuntu installs a setting in a different location than the standard and the settings software of Gnome crashes if you try to use the correct location in Ubuntu.

**Comment by CircuitCoder** [comment]
The latest commit works fine on my computer. Thanks!
