### ISSUE TITLE
Transparency isn't updated when you switch workspaces & rounded corners

### ISSUE THREAD

**Issue by Mancooo** [rockon999/dynamic-panel-transparency#45]
Hi,

There are two bugs which affect this extension for me;

1. When you switch workspaces with for example Super + page down/page up, or with the workspace switcher extension, the top bar stays opaque (when you leave a workspace with a maximized window). This updates only when going into the overview or open an unmaximzed window. 

2. I find the rounded corners more pleasant to look at, so I keep top bar with rounded corners. However even with the rounded corners the bar switches between round and flat when maximizing/unmaximizing, you see a quick animation. So when there are rounded corners and I maximize a window, the top bar goes flat and then rouned again very fast.

**Comment by rockon999** [comment]
Hello! I'd like to fix these issues as soon as possible!

In regards to #1 I do not experience this on my installation. I used Workspaces to Dock and shortcuts to switch between workspaces and the panel always faded out. Are you on the latest version from Gnome Extensions? If so, could you please provide any output from `journalctl --since "30 seconds ago"` after the failure to fade occurs?

#2 is actually a known issue. The problem with the corners is the way the shell generates them. In the past I've had to either have them appear suddenly before and/or after the fade. I may have just found a method of fading them smoothly, but it may cause some lag in other transitions... so I'll have to debug it. I'll try to publish an experimental fix within the next few days. Thanks for reminding me of this issue, I don't personally use the corners and I had forgotten the visual glitch that accompanies them currently.

**Comment by Mancooo** [comment]
Thank you for your quick response.

In regards to #1, I experience this bug (while using V16 of your extension on Fedora 24/25) while switching from a workspace with a maximized window to a new workspace either by doing Super+page down/up or by switching workspaces with the extension Workspace Indicator (https://extensions.gnome.org/extension/21/workspace-indicator/) by scrolling with my mouse scrollwheel or simply by selecting a different workspace.

The output of `journalctl` --since "30 seconds ago"` is as follows:

journalctl --since "30 seconds ago"
-- No entries --

The bug does not happen when a window is maximized but on the background with a unmaximized window in front of it and doing the same actions as above OR when going into the overview and then moving up or down with page up/down. 

In regards to #2, thanks! With the extension Activities Configurator ([https://extensions.gnome.org/extension/358/activities-configurator/](url)) the round corners always stays round and there is no switching. 

Let me know if I can help, thank you again for this great extension.

**Comment by rockon999** [comment]
A few questions...
Are you on Wayland? What version of Gnome Shell are you using?

**Comment by rockon999** [comment]
Also, do you still have Activities Configurator installed?

**Comment by Mancooo** [comment]
I primarily use X.org, because Wayland has 1 or 2 (small) issues for me. But these bugs occur on X.org as well as on Wayland. It makes no difference. 

I am on shell version:

$ sudo dnf list gnome-shell
Installed Packages
gnome-shell.x86_64                                           3.22.1-2.fc25

Right now I dont have Activities Configurator installed, but I used it to test how it handled a transparant top bar (with rounded corners).

**Comment by rockon999** [comment]
I can't replicate on my base system (Arch Linux, Shell 3.22.1), so I'll spin up a Fedora virtual machine this weekend and see if I can't replicate the bug. If you had time to do a screencast of both issues I'd very much appreciate it! Gnome Shell has builtin screencasting... just press `Alt+Ctrl+Shift+R`.

**Comment by Mancooo** [comment]
I have both bugs screencasted:

https://www.dropbox.com/s/xrhjpmfqp4ez956/Screencast%20from%2011-23-2016%2010%3A43%3A45%20AM.webm?dl=0

https://www.dropbox.com/s/mhy5voc87inrrp4/Screencast%20from%2011-23-2016%2010%3A44%3A46%20AM.webm?dl=0

**Comment by rockon999** [comment]
I've reproduced the bug! It seems that when there aren't any individual application overrides set in App Tweaks the panel fails to update when switching workplaces. If you want a temporary fix go to `"App Tweaks" > "Advanced"` and type `DropDownTerminalWindow`. I'll patch this bug over the weekend.

**Comment by rockon999** [comment]
Also, the corner fix is almost debugged!

**Comment by Mancooo** [comment]
Whoah, that is excellent!

**Comment by rockon999** [comment]
The latest GitHub should fix these bugs! If you had time to test it out that'd be great!

**Comment by Mancooo** [comment]
I tested it with Xorg and Wayland, the bugs are fixed! Thank you very much!

**Comment by Mancooo** [comment]
Found a tiny bug...

When playing a movie with VLC the transparancy also does not update. 

When you watch a movie and switch to fullscreen (either by hitting the F key or double clicking with the mouse) and back to windowed mode, the top bar stays opaque.

**Comment by Mancooo** [comment]
MPV does not show the same behaviour...only VLC

**Comment by rockon999** [comment]
That latest commit should fix this issue. I'm currently testing this new fix along with the older fixes for the previous issues.

**Comment by Mancooo** [comment]
The VLC bug is fixed with the latest commit!

**Comment by Mancooo** [comment]
FYI, with this latest build the extension does not load on resume from suspend, gnome tweak tool says "error loading extension"

**Comment by rockon999** [comment]
I've noticed this too. Working on a solution.

**Comment by rockon999** [comment]
The latest should fix your issues and solve the suspend issue. Thank's for bearing with me. Gnome Shell can be finicky and there are a lot of varying setups that make debugging quite interesting.

**Comment by Mancooo** [comment]
Fixed again! Thanks!

I do notice that after resuming from suspend, the top bar flashes (really fast) from black to transparant. It seems the extension is reloading itself after suspend/resume. I don't know if that is the expected behaviour.

**Comment by rockon999** [comment]
It is. Gnome Shell disables and enables all extensions when it suspends and/or locks. I'm still trying to improve the effect.

**Comment by Mancooo** [comment]
Ok, thanks for the explanation. That's bummer that Gnome Shell does that, visually it detracts from the otherwise very awesome extension that Dynamic Panel Transparancy is. 

Thanks for all your hard work!

**Comment by rockon999** [comment]
I think the latest should help reduce the flashing effect. If you set a custom panel color it will still be a little off, but for darker colors (like black) it shouldn't flash.

**Comment by Mancooo** [comment]
Ooh that's very nice, it smoothly fades out from black to transparant! 

I also tested with a custom panel color, in that case it also fades out from black (instead of the chosen color) to transparant, I guess that is fine, because using a custom color is maybe not that common.

**Comment by rockon999** [comment]
What I did was have it fade from whatever color the shell theme you're using is. I think that is the only way to prevent the flash some users experience. Personally, I use a theme that already has a transparent top bar (Copernico) so I've never experienced the flash outside of testing.

**Comment by Mancooo** [comment]
Ok, I think the extension is very nice at the moment! I can't wait for the definitive update, lots of fixes :)

**Comment by rockon999** [comment]
The changes that fixed this issue have been included in v18, the latest stable release. This release is currently pending review on Gnome Extensions. As such, this issue is now closed.
