### ISSUE TITLE
Panel does not become transparent when using "show desktop" shortcut

### ISSUE THREAD

**Issue by michael-rapp** [rockon999/dynamic-panel-transparency#46]
I am using the latest version of the extension on Gnome 3.22.2 with Wayland running. I often show the desktop (by hiding all windows) using a keyboard shortcut and the panel transparency is not adjusted in such case. Therefore, if a window is shown fullscreen and the panel is opaque, it does not become transparent when hiding that window using the shortcut. 

The shortcut I use can be found in Gnome's keyboard settings in the "Navigation" section. It is called "Hide all normal windows". I think, it is not set by default. However, I like to use it and set it to Super + D.

**Comment by rockon999** [comment]
The issue is that the shortcut you are referencing doesn't actually do what most people think it does. You would think it hides all the windows... instead it takes the "desktop" (which is actually just a special type of window) and puts it above all the other windows so you can't see them. The issue is that there is no way to detect the type of window the desktop is... making it rather impossible to support the shortcut. I have looked into this before and I've simply never found a way to make this possible. Hopefully I'll be able to find a solution eventually, but for now I don't see any way to fix this issue.

**Comment by michael-rapp** [comment]
Okay...this is actually some unexpected behavior. If it is not possible to fix this issue, it is not that bad, because it is only an edge-case I wanted to point out.

However, if it is so hard to detect these events, I wonder how e.g. the DashToDock extension is able to handle it. When its intelli-hide feature is enabled, the dock becomes visible, if it is not overlayed by a window. And this works fine, when pressing the shortcut I was talking about. Maybe taking a look into that extension's source code or talking to the developer could help...

**Comment by rockon999** [comment]
I've looked into what DashToDock is using and I'm not sure if the way it detects windows will be feasible in this extension (or fix the issue). I'll have a look this weekend and see if I can't fix it. I haven't looked at this in a while so it's entirely possible I missed this last time.

**Comment by rockon999** [comment]
Also, quick question. Are you using desktop icons?

**Comment by michael-rapp** [comment]
Yes, but the issue remains when disabling them.

**Comment by rockon999** [comment]
I don't believe I can use the same method Dash to Dock uses, but I have discovered a way to detect this shortcut when desktop icons are enabled. I'll push this fix with the next version. This should fix most use cases as I'm guessing users who don't use desktop icons rarely show their desktop.

**Comment by michael-rapp** [comment]
Sounds sufficient to me.

**Comment by rockon999** [comment]
The changes that fixed this issue have been included in v18, the latest stable release. This release is currently pending review on Gnome Extensions. As such, this is issue is now closed.

**Comment by 9Morello** [comment]
@rockon999 Hello, thanks for solving this issue. How long does it take before it arrives on Gnome Extensions?

By the way, this extension improved a lot since I used it over a year ago, congrats.

**Comment by rockon999** [comment]
It should be live now.
