### ISSUE TITLE
[fixed: dynamic panel + guake ...] Add per-app configuration.

### ISSUE THREAD

**Issue by db0x** [rockon999/dynamic-panel-transparency#5]
if guake is not maximized and placed on top the panel is transparent 

enhancement would be to define windows like guake in settings with an deviant aplha-value

**Comment by rockon999** [comment]
This *should* be possible. I'll consider implementing it once I've finished and debugged the core functionality of the extension.

**Comment by db0x** [comment]
:) fine ... maybe think about to define windows with deviant alpha + color  ... than it is possible to colourize the panel if an error-dialog is in front -> red etc

**Comment by quasipedia** [comment]
:+1: This extension is really nice and smooth out the UI in the shell... The transparent bar on top of guake is just a violent punch in your eyes! :facepunch: :cry: 

:smile:

**Comment by rockon999** [comment]
I've decided to go a different route. Instead of a list of apps that don't trigger transparency I'm adding the option to darken the panel when a window touching the panel is maximized horizontally. This feature is available in the [development branch](https://github.com/rockon999/dynamic-panel-transparency/tree/development) for testing. :smile:

**Comment by quasipedia** [comment]
@rockon999 - I think the way you are going about is best for the given case.

Additionally, I think having a generic, configurable override would be very helpful per se (there may be instances in which you may want to have the dark bar (or even colorize it in red) when you open a specific application).

**Comment by db0x** [comment]
+1 @quasipedia

**Comment by rockon999** [comment]
I think this new feature will apply to numerous cases, but I will work on a per-app override.

**Comment by quasipedia** [comment]
@rockon999 - :+1:  I have no doubt that the way you are solving it now will **fix** for virtually all cases were the visualisation is currently broken.  The "per app" configuration is really aiming to add flexibility to the extension and may in fact be considered a **new feature** entirely. :smile:

**Comment by rockon999** [comment]
For all concerned per-app configuration is slated to be the next major addition to the extension. I'm still exploring the best method to detect specific apps and store their individual settings.

**Comment by rockon999** [comment]
An experimental version of per-app support will be enabled in v10 or v11. Thanks for your suggestions!

**Comment by rockon999** [comment]
Update: v11 is set to be released in the upcoming weeks with this feature. I've entered final bug testing and am establishing compatibility with shell versions 3.14-3.20.

**Comment by rockon999** [comment]
v11 is now in the master branch. This is a major rewrite so some bugs may occur. If you have any time to test the new version I'd very much appreciate it!

Thanks!

**Comment by rockon999** [comment]
Finally... This is done! Implemented in v11. Thanks for your suggestions!
