### ISSUE TITLE
Upload to extensions.gnome.org

### ISSUE THREAD

**Issue by surajmandalcell** [rockon999/dynamic-panel-transparency#50]
### Please upload the extension to extensions.gnome.org for easier installition.

**Comment by rockon999** [comment]
While the current GitHub is ahead of Gnome Extensions (due to lack of time for official release testing on my part), the extension is indeed on extensions.gnome.org. [Link.](https://extensions.gnome.org/extension/1011/dynamic-panel-transparency/)

**Comment by surajmandalcell** [comment]
oops...sorry, my bad ;-;
