### ISSUE TITLE
Panel not adapted when moving maximized window to different monitor using shortcuts

### ISSUE THREAD

**Issue by michael-rapp** [rockon999/dynamic-panel-transparency#51]
I found an edge case, where the state of the panel is not properly updated. It happens when moving a maximized window from the primary screen to a secondary screen or vice versa by using a shortcut. Such shortcuts can be configured in the "Keyboard" panel of the Gnome settings, e.g. "Move window to monitor to the right". 

If a maximized window is shown on the primary screen, the panel is opaque at first. Using shortcuts to move the window to another screen does not cause the panel to become transparent, even if there are no maximized windows left on the primary screen. The other way round, the panel does not become opaque when moving a maximized window from the secondary screen to the primary screen.

**Comment by rockon999** [comment]
I'm just preparing to release v18 now, but I can try to include a fix for this too. The latest commit has some possible fixes. I currently don't have a multi-monitor setup to test this on, so your input would be great!

Thanks!

**Comment by michael-rapp** [comment]
I am currently not at home, but I will be able to test it tomorrow. The changes are on the master branch, right?

**Comment by rockon999** [comment]
Yes.

**Comment by michael-rapp** [comment]
Sorry for the late reply. I just tested the current master branch and the issue is now gone. Thank you very much!

**Comment by rockon999** [comment]
The changes that fixed this issue have been included in v18, the latest stable release. This release is currently pending review on Gnome Extensions. As such, this issue is now closed.
