### ISSUE TITLE
When leave overview, panel transition starts after overview animation ends.

### ISSUE THREAD

**Issue by lixiaoyan** [rockon999/dynamic-panel-transparency#52]
These two animations should start together.

**Comment by rockon999** [comment]
While this might be more visually appealing (depending on your specific settings), it is not practical for the extension. It would require some hack-y/messy code and, in my opinion, the benefits do not out weigh the costs in this situation. It likely would be less reliable than the current method and more likely to break other extensions. I would recommend lowering your transition time if the visuals aren't working for you.

I will look into the possibility of starting the transition sooner, but it will most likely never be exactly when the overview animation starts.

Thanks for reporting this issue!

**Comment by lixiaoyan** [comment]
Seems it works well in old release, I upgraded this plugin yesterday and found this behavior changed. I don't remember the version before I upgrade it.

**Comment by rockon999** [comment]
Okay, in that case, there is little that has changed in the actual handling of the overview. However, more has been added to the plugin logic that could slow it down. If you go into the plugin preferences... into "App Tweaks" try removing any applications and see if that helps the plugin speed up. The latest update to the extension (currently in review) will remove some of the speed issues with App Tweaks.

**Comment by rockon999** [comment]
Hi! Is this issue still affecting your installation?

**Comment by MartinPL** [comment]
Still here:
https://youtu.be/0nDvyVpu3Iw

**Comment by rockon999** [comment]
Okay, I've thought about this issue a lot and I don't see any real way to solve it. There are several problems at play here. I don't really know what order the windows are until after the user has left the overview. If a user clicks on a particular window, for instance, it could completely change the ordering and/or focus. This matters as several other settings are dependent on which windows are higher and/or maximized. While I may be able to work around that issue, there is also a performance issue. If I try to run my calculations and animations while the overview is still running, both animations will suffer and the result will most likely be laggy on many systems. And finally, I personally prefer this style. In my mind it makes the most sense to have the panel animate in after the overview is animated out just like the panel animates out after the overview animates in.

**Comment by Mancooo** [comment]
Hi, I also have this issue. I am running the latest code from Github. I have animations turned off. In that case the transition is even more "ugly". There is a flash between the transition from overview to a maximized window.

**Comment by rockon999** [comment]
@Mancooo The extension does have a 'force animation' option that will enable animations only for the panel. Otherwise, I do have a fix for users with disabled animations. I'm going to explore the best way to possibly fix this for those with enabled animations too, however. The issue is that on some systems running my logic code during the overview transition causes lag. Give me some time and I'll see if I can't work it out. :)

**Comment by Mancooo** [comment]
Thank you for the quick response and the suggestion!

Op 26 apr. 2017 03:06 schreef "Evan Welsh" <notifications@github.com>:

**Comment by rockon999** [comment]
@Mancooo The latest should fix the issue for those without animations enabled, I'm still working on solutions for everyone else.

**Comment by Mancooo** [comment]
Man, you are totally awesome! The latest version fixes the issue for me!

**Comment by rockon999** [comment]
I have thought about this issue for some time and have decided to table it for now. I prefer the animation occurring after the overview in the extension and currently that is best for performance's sake. However, I understand why you may want this feature. For now I'll fix it for those with animations disabled and consider adding a setting in preferences to change this behavior in the future.

**Comment by lixiaoyan** [comment]
It seems working fine with the latest commit! Thanks a lot!
