### ISSUE TITLE
Changing workspaces bug

### ISSUE THREAD

**Issue by DavidGitta** [rockon999/dynamic-panel-transparency#56]
When you have two workspaces for example. The first workspace has a maximized window open and the second has no window open at all. If you switch from the second workspace to the first, it won´t adjust the panel-transparency / opacity.
(The other way around it is working correctly.)
(If you have a not maximized window open on the second workspace, it is working correctly.)

**Comment by rockon999** [comment]
Hi!

I believe this issue has just been solved. Please try the latest on the GitHub. See #55 please.

**Comment by DavidGitta** [comment]
Yes, I can confirm it is solved in "the latest on GitHub".
Btw. Thanks for this awesome extension!
