### ISSUE TITLE
Blur out background option

### ISSUE THREAD

**Issue by salevdns** [rockon999/dynamic-panel-transparency#57]
# Enhancement idea
The idea is that the top bar can optional blur out the background behind it in both statuses individual.
[To get for example a look similar to macOs.
](https://www.intego.com/mac-security-blog/wp-content/uploads/2015/10/reduce-translucency.png)
Concept:
![image](https://cloud.githubusercontent.com/assets/24809481/23857594/1c0db3e8-07fe-11e7-9e9a-9b313b366237.png)

**Comment by DavidGitta** [comment]
Maybe even with an with a blur % regulator like for the opacity.

**Comment by DavidGitta** [comment]
I think it would work best with a 2 layer concept: the blur under the opacity.

**Comment by rockon999** [comment]
I'll look into and consider this when time permits. I have quite a few other enhancements currently in line, so I can't guarantee when (or if) this will be added. Thank you for contributing!

**Comment by Alexander-Wilms** [comment]
The Blyr extension uses a shader to blur the dash background (as well as the panel background): https://github.com/yozoon/gnome-shell-extension-blyr

Maybe this could be re-used.

**Comment by rockon999** [comment]
@Alexander-Wilms  @salevdns As of the latest Blyr version and Gnome Shell 3.26 our extensions are compatible and Blyr will blur the panel. Thus this enhancement is no longer needed. Thanks for the ideas!

**Comment by rockon999** [comment]
Closed.

**Comment by jsebean** [comment]
Can this be reopened? It would be nice to have a blur option in dash to panel, as while the blyr extension does work, it does not have any affect on panels on other monitors.
