### ISSUE TITLE
Lag when exiting overview/all windows spread mode.

### ISSUE THREAD

**Issue by groudie** [rockon999/dynamic-panel-transparency#59]
First off, thanks for the hard work. You've got a useful and wonderful project going here. 

When I press the super key to spread the windows and I press again to exit there is some lag. The transition isn't smooth. I've isolated the issue to dynamic panel transparency as it happens when only it is enable. The problem persists even in Wayland as well as Xorg. 

Dell Inspiron 7537
16GB RAM
Core i7 Haswell(mobile) 
Manjaro 17.0
3.22.2

**Comment by rockon999** [comment]
Is the lag both enter and exit or only on one of the two?

**Comment by groudie** [comment]
@rockon999 It happens only when I exit window spread mode.

**Comment by rockon999** [comment]
@groudie I'm looking into this. I'll push some possible fixes tonight or tomorrow at some point.

**Comment by rockon999** [comment]
@groudie Could you try the latest on the GitHub? I've optimized the hiding code and eliminated some possible lag-related issues.

**Comment by groudie** [comment]
@rockon999 Thanks for the quick response and your efforts to get this resolved so soon. I tried the latest(master branch) but unfortunately the issue is still there.

**Comment by rockon999** [comment]
@groudie I've pushed some more work. Let me know how it treats you. Thanks!

**Comment by groudie** [comment]
@rockon999 Just tried the latest from the master branch. It's still lagging. It's worth mentioning that this started happening after gnome shell pushed a notification to me saying that there was an update to Dynamic Transparency Panel and I went to the gnome shell extensions website to update the extension. I can confirm this on two different laptops and on two separate days.

**Comment by rockon999** [comment]
@groudie Could you send me your extension preferences so I can replicate your setup?

**Comment by groudie** [comment]
@rockon999 
These were the only 2 sections where I made modifications. Everything has their default config.
![dpt2](https://cloud.githubusercontent.com/assets/7927434/24371240/b244a1e0-12d6-11e7-9de8-ea9b985d2c3d.png)
![dpt3](https://cloud.githubusercontent.com/assets/7927434/24371241/b25c6ad2-12d6-11e7-8d16-ba547b19963f.png)

**Comment by rockon999** [comment]
@groudie I can keep looking into this, but as far as I can tell I've optimized the code as best I can. The fact of gnome shell is that sometimes animations aren't perfect. You could try 'force animation'. That occasionally fixes issues, but I can't guarantee that. A few more questions...

1. How many windows do you usually run?
2. Is the lag always present?
3. Is there any way you could post a screencast of it?

**Comment by rockon999** [comment]
@groudie Before those questions... I was unable to reproduce on my AMD card but my Intel card does show some of these issues. I've made some changes to the handling of the overview that may reduce overall lag. Could you try the master again? Thank you so much for helping with this testing!

**Comment by groudie** [comment]
@rockon999 Sorry for the late response. Unfortunately I still have the issue even with the latest changes.  I've provided a screen cast of the issue in the link provided below.

http://www.dailymotion.com/video/x5gj87p

**Comment by groudie** [comment]
@rockon999 Happy to report that the issue was fixed! Thanks for the hard work and diligence. How did you resolve the issue?

**Comment by rockon999** [comment]
@groudie  For some reason Gnome was firing a 'window entered monitor' event when the overview was transitioning. This was causing the extension to run too intensive and repetitive logic during the overview transition. Supporting so many different systems with so many different configurations means that fixing one thing often breaks another, and in this case a fix for multi monitor folks also messed up animations for some systems.

**Comment by rockon999** [comment]
@groudie  Hi! Could you test the master one last time? I've had to change the code a bit for the final release. Thanks!

**Comment by groudie** [comment]
@rockon999 Thanks for explaining the situation. It is loads better and I understand the constraints you are working with here. At this point I think you can safely label the issue fixed now.
