### ISSUE TITLE
Custom panel color ignored after unlocking session with maximized window

### ISSUE THREAD

**Issue by Saend** [rockon999/dynamic-panel-transparency#60]
Hi! Here's my issue:

I set a panel colour in the Background setting tab. 
If I leave a window maximized and then lock my screen, either manually (Super+L) or by suspending/hibernating, when I unlock it the panel colour is back to the default black. 
Unmaximizing and maximizing again, or going to the overview and back fixes it.

I use the latest commit (b1316c9), GNOME Shell 3.22.3 on Arch Linux.
I love this extension!

**Comment by Saend** [comment]
It would seem the shell theme is at fault here. I tried the various themes I have installed: No issue with the default theme or zuki-shell. But Arc, Vertex and Deepin don't work as expected.

**Comment by rockon999** [comment]
Hi! Certain themes have settings that mess with the extension. If you go into the extension preferences and click 'remove excess panel styling' that should fix most issues. I'll try to make that more clear in future releases.

**Comment by Saend** [comment]
Unticking it fixed it. Thanks!
