### ISSUE TITLE
Showing Desktop Doesn't Trigger Animation

### ISSUE THREAD

**Issue by ksthiele** [rockon999/dynamic-panel-transparency#62]
If you have (a) window(s) open and press Ctrl + D to show desktop the panel doesn't get transparent

**Comment by rockon999** [comment]
Please see issue #61 and/or #46. The primary issue is detecting the command. Currently it works fine if you have desktop icons enabled, so I would recommend enabling them in Gnome Tweak Tool and then removing any unwanted icons from your desktop.

**Comment by rockon999** [comment]
@ksthiele If you could please try the latest from the GitHub, I think I may have found a solution to this issue. Thanks :)

**Comment by michael-rapp** [comment]
I can confirm that it now works. Great work!
