### ISSUE TITLE
Vertically maximized windows aren't always detected

### ISSUE THREAD

**Issue by sojusnik** [rockon999/dynamic-panel-transparency#63]
Although a window is vertically maximized before, it isn't recognized as such by your extension, upon another launch. You have to maximize it again vertically, f.i. by double-clicking on the header, as shown in [this](https://mega.nz/#!u5AXACZL!EAs-oAjh9JpARB_A83y7wiNSzir_3JcPxhp_vKktvvk) video.

Any ideas why?

Happens on Ubuntu Gnome 17.04 with mostly Gnome 3.24.

**Comment by rockon999** [comment]
This issue is that Firefox doesn't actually maximize the window. It just opens a new window that is the same size in the same position. It isn't, however, maximized. Maximized is actually a window "state" which is detected by this extension. Firefox never sets this state. I'll look into this, but I think this may be a Firefox bug.

**Comment by sojusnik** [comment]
I've tried it with the Opera browser and LibreOffice Writer and got the same result.

**Comment by rockon999** [comment]
Okay, so it isn't a Firefox specific bug. But something in the system isn't remembering vertical maximization. It appears to work fine when the window is also maximized horizontally. I'll keep investigating.

**Comment by rockon999** [comment]
I'm working on a more intelligent window detection system that can deal with windows that aren't actually maximized but "should" be or appear to be. It should be ready for release soon.

**Comment by rockon999** [comment]
The latest from the GitHub has implemented the advanced detection system! That should prevent these errors in detection moving forward.

**Comment by sojusnik** [comment]
Did you already publish it to https://extensions.gnome.org/? I'm asking, since I didn't receive any update there.

**Comment by rockon999** [comment]
It hasn't been published yet. I'm planning to publish this week.

**Comment by rockon999** [comment]
Closing, v21/v22 are pending review on Gnome Extensions.
