### ISSUE TITLE
panel doesn't update state after super + D (show desktop)

### ISSUE THREAD

**Issue by mmccoy37** [rockon999/dynamic-panel-transparency#64]
I am on debian stretch. If I press super+D it will show desktop but the panel will not change to transparent unless I open a windowed app.

Is this something which can be added?

Thanks,
Matt

**Comment by rockon999** [comment]
Please see issue #62, #61, #46. The primary issue is detecting the command. Currently it works fine if you have desktop icons enabled, so I would recommend enabling them in Gnome Tweak Tool and then removing any unwanted icons from your desktop. As of #62 a complete solution has been found, however, and I am currently debugging it for the next release.

Thanks, 
Evan

**Comment by franglais125** [comment]
Here is a fix from upstream, for the built-in transparency coming in Gnome 3.26. The trick is to use the `notify::visible` window signal.

https://git.gnome.org/browse/gnome-shell/commit/?id=292ac413c80f3fdd907dec14468638647de2466e

**Comment by rockon999** [comment]
Closing, fixed in v21/v22 which are currently pending review on Gnome Extensions.
