### ISSUE TITLE
Activate transparency when a window covers part of the panel.

### ISSUE THREAD

**Issue by Isaac-bankier** [rockon999/dynamic-panel-transparency#65]
It would be cool if when a window moves behind the panel it would no longer become transparent.

**Comment by rockon999** [comment]
Hello...

I've started work on an advanced window detection system per #63 and will try to include this in that work!

Thanks for the suggestion!

**Comment by Isaac-bankier** [comment]
That's great!

This is one of my favourite extensions so its always good to see more features being added.

**Comment by rockon999** [comment]
The latest in the GitHub implements this feature :)

**Comment by Isaac-bankier** [comment]
Cool thanks!
