### ISSUE TITLE
No transparency in latest version of Solus - Maybe GTK incompatibility

### ISSUE THREAD

**Issue by hhiru** [rockon999/dynamic-panel-transparency#66]
What version of GTK do I need to use this extension? I'm using the latest version of [Solus](https://solus-project.com/)

**Comment by rockon999** [comment]
Hi! This is a Gnome Shell extension, so it only works under the Gnome Shell desktop environment. Solus uses Budgie.

**Comment by hhiru** [comment]
Nope. Solus uses multiple environments, Gnome is one of those. You can chose the environment you want in the download section of SolusProject

**Comment by rockon999** [comment]
Okay, sorry, I was unaware of this. This extension doesn't depend on GTK. It depends on Gnome Shell, which uses a different toolkit to draw itself (st). What Gnome Shell version do you use?

**Comment by hhiru** [comment]
GNOME Shell 3.24.1

**Comment by rockon999** [comment]
Could you try enabled/disabling the extension in Tweak Tool and sending me the relevant log entries from `journalctl --since "30 seconds ago"`

**Comment by hhiru** [comment]
Now it works! I enabled it and it works for some reason D:

**Comment by rockon999** [comment]
Hm. Would you be able to send me any log entries from when you attempted to turn the extension on? Also, do you have animations enabled?
