### ISSUE TITLE
Transparency bug on switching windows

### ISSUE THREAD

**Issue by Haarolean** [rockon999/dynamic-panel-transparency#67]
Hello, just updated with latest version of the extension from extensions.gnome.org and noticed this: after maximizing windows, hiding and showing them back — animation is sorta stuck unfinished, transparency is neither 100 nor 0 until I resize the window again.
bugged:
![bugged](https://cloud.githubusercontent.com/assets/1494347/26554373/76d14142-4498-11e7-997b-4c2e41059a50.png)
normal one:
![normal](https://cloud.githubusercontent.com/assets/1494347/26554372/76d09850-4498-11e7-9a99-c685d10a8e8e.png)

**Comment by rockon999** [comment]
Hello,
What exactly are you using to 'hide/show' the windows?

**Comment by Haarolean** [comment]
Simply pressing minimize button :)

**Comment by rockon999** [comment]
And how are you bringing it back? Also, do you have animations enabled? And have you changed any extension settings?

**Comment by Haarolean** [comment]
I'm switching it back by clicking on window' icon in dock (plank), Minimizing and maximizing the window after helps to fix the issue. I guess all the settings are defaulted at the moment, transition style is default (linear). Animations in tweak tool are enabled as well, if you mean that thing.

**Comment by rockon999** [comment]
What shell version are you on? And when this happens could you type `journalctl --since "30 seconds ago"` into your terminal and see if anything is erroring?

**Comment by Haarolean** [comment]
I'm on 3.24.1, journalctl says there are no entries. But viewing the log manually gives this:
Dunno if this helps.

> -- Logs begin at Mon 2017-05-29 06:14:08 MSK, end at Mon 2017-05-29 23:19:12 MSK. --
май 29 23:14:52 haarolean-laptop.cronfire.ru gnome-software-service.desktop[21808]: 20:14:52:0090 Gs  no app for changed native-window-placement@gnome-shell-extensions.gcampax.github.com
май 29 23:14:52 haarolean-laptop.cronfire.ru gnome-shell[21666]: loading user theme: /usr/share//themes/Arc-Dark/gnome-shell/gnome-shell.css
май 29 23:14:52 haarolean-laptop.cronfire.ru gnome-shell[21666]: Ignoring length property that isn't a number at line 732, col 24
май 29 23:14:52 haarolean-laptop.cronfire.ru gnome-shell[21666]: [Dynamic Panel Transparency] Using theme data for: Arc-Dark
май 29 23:14:52 haarolean-laptop.cronfire.ru gnome-shell[21666]: Ignoring length property that isn't a number at line 732, col 24
май 29 23:14:52 haarolean-laptop.cronfire.ru gnome-software-service.desktop[21808]: 20:14:52:0168 Gs  no app for changed dynamic-panel-transparency@rockon999.github.io

**Comment by rockon999** [comment]
I'll look into this more as the week progresses. I may have an idea of why it isn't currently functioning properly, but I'll have to test it. I'm currently in finals week, so my work is rather limited. One final question, though, are you on X11 or Wayland?

**Comment by Haarolean** [comment]
Good luck with your exams :)
I'm on x I guess, if the defaults in my distro haven't changed suddenly.

**Comment by rockon999** [comment]
Hi!

Could you try the latest from the GitHub? I think the newest version may solve your issue. Thanks!

**Comment by Haarolean** [comment]
Sorry for the delay. Pulled your git version, can't reproduce the bug, seems fine now. I'll reply if I'll get that again. Thank you for the fix and your extension :)

**Comment by rockon999** [comment]
Fixes published to Gnome Extensions in v21/v22, pending review.
