### ISSUE TITLE
TypeError: Main.screenShield is null 

### ISSUE THREAD

**Issue by addadi** [rockon999/dynamic-panel-transparency#7]
Hi,
Using gnome-shell 3.18 I'm getting the following error when enabling (which doesn't succeed):
Gjs-Message: JS LOG: Extension "dynamic-panel-transparency@rockon999.github.io" had error: TypeError: Main.screenShield is null

Checked this with looking glass and indeed no surprises Main.screenShield is null. oviously it doesn't have a connect method or an _isActivated property. I guess this is what causing the enable function to fail at line 69 (trying to set this._lockScreenSig)
thanks

**Comment by rockon999** [comment]
Hi! This is an oversight on my part. Main.screenShield only exists if Gnome Shell handles your locking mechanism. I'll add the relevant code in to check for this!

**Comment by addadi** [comment]
fixed and working. thanks!
