### ISSUE TITLE
Triggering Dynamic Panel Transparency Exclusively with Tilix's Quake Mode

### ISSUE THREAD

**Issue by OriginalFannibal** [rockon999/dynamic-panel-transparency#73]
This isn't a bug with the extension but something I wanted to discuss. I am sorry if this isn't the right place to do so.

I use [Tilix](https://github.com/gnunn1/tilix) as my terminal and it offers a really handy quake mode. This mode is just a regular Tilix window with a fixed location (directly underneath the status bar) and spanning the width of the screen. As it isn't a maximized window it doesn't trigger dynamic panel transparency, resulting in this appearance.

![screenshot from 2017-09-13 18-44-52](https://user-images.githubusercontent.com/20235646/30379300-8d0b1d98-9885-11e7-923f-ae8b337ecc60.png)

I used the settings to set the panel to always trigger when using Tilix but I can only set this on a per-app basis or on the basis of the WMClass. Quake mode is just Tilix launched with the `-q` flag and so it is the same app and has the same WMClass. So right now, the only way I can get it to trigger for Quake mode also triggers it when using it regularly. This is what it looks like then.

![screenshot from 2017-09-13 18-56-06](https://user-images.githubusercontent.com/20235646/30379779-25b2223e-9887-11e7-9704-7553d4563c38.png)

I really hope you don't think I am complaining. I just want your opinion on if there is something I can do to trigger dynamic panel transparency when using Quake mode but not when launching the regular terminal.

**Comment by rockon999** [comment]
The latest version on the GitHub should hopefully fix these problems! I've been very bogged down by work and university so I haven't had a lot of time to release a new version officially. I'm trying to get to that this week.

**Comment by OriginalFannibal** [comment]
Tested v21 and it does fix this. Thank you so, so much! Noticed that it also triggers for other apps that touch the panel. You are amazing :)

**Comment by rockon999** [comment]
I'll close it when it is officially released!

**Comment by OriginalFannibal** [comment]
Just noticed that v22 is up on Gnome Extensions and carries this fix. Hope you don't mind me closing this.
