### ISSUE TITLE
Gnome 3.26 warnings

### ISSUE THREAD

**Issue by vans163** [rockon999/dynamic-panel-transparency#74]
JS WARNING: [/home/user/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/prefs.js/preferences/main.js 376]: Too many arguments to method Gtk.ListBox.set_sort_func: expected 1, got 2

JS WARNING: [/home/user/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/util.js 106]: Too many arguments to method Gio.File.replace_contents: expected 5, got 6

Seems https://github.com/rockon999/dynamic-panel-transparency/issues/71 did not fix all of them.

**Comment by rockon999** [comment]
Gnome made some changes in 3.26 and some previously valid code is no longer correct. I've corrected these issues and pushed the changes. I'll release them on Gnome Extensions as soon as possible.

**Comment by vans163** [comment]
I am so annoyed at Gnomes lack of deprecation.

**Comment by rockon999** [comment]
The main issue is that the only API versions that are actually documented well are 3.14 and 3.22. I used 3.14 reference to write sections of the extension (3.22 references only came out in the past few months) and until 3.26 Gnome continued to allow old method calls (for instance calls with extra parameters) w/o warning. The new version of GJS (gnome javascript) however provides warnings for such events.

**Comment by vans163** [comment]
warning are gone for me on latest master.

**Comment by rockon999** [comment]
Fixes published to Gnome Extension, awaiting approval. Closing.
