### ISSUE TITLE
Is it possible to move windows behind a 100% transparent bar?

### ISSUE THREAD

**Issue by vans163** [rockon999/dynamic-panel-transparency#75]
The default behaviour when a window touches an edge is to maximize.

If using a 100% transparent bar, even when touching it, to reclaim extra screen-space and to follow intuitivity, you want to move windows behind the transparency.

But its a hard block and the window that touches the transparent section immediately maximizes.  Is it possible to apply a style or option to not make windows maximize upon touching the 100% transparent bar, and ideally act as if nothing is there, to be able to slide behind?

**Comment by rockon999** [comment]
Gnome itself creates the barrier, and it is not really this extension's purpose to move windows behind the bar. The latest from this GitHub (and the version pending approval on Gnome Extensions) does however make the panel transparent when windows overlap with it. You can hold a key to move a window around (clicking anywhere on the window) and past the barrier. The key on my system is Alt and it is fairly standard..

**Comment by vans163** [comment]
Alt does not seem to be doing anything for me, but I can understand if its out of scope of this plugin.  I do wonder if there is a way to do it though, I tried display: none, pointer-events: none, and some other style fixes. None seemed to do it.

**Comment by rockon999** [comment]
@vans163 If you go to `org → gnome → desktop → wm → preferences → mouse-button-modifier` in dconf, whatever key is defined there will be the key that allows you to drag windows anywhere while that key is held.

**Comment by vans163** [comment]
Cool! Did not know that. I got it to slide behind now, but it still "locks/hits a wall" when you first drag it up, then another drag slides it under.  But then if you release the key (for me Super was the key), you cant click on it again, since the topbar even with 100% transparency does not allow clicking through it!

**Comment by rockon999** [comment]
@vans163 When you're grabbing the window using the mod key grab it by the window content not the title bar. Also, I do know that Dash to Panel allows you to remove barriers when the panel is on the screen bottom, but I think it keeps the barrier on the top.

**Comment by vans163** [comment]
@rockon999 thanks, I did not know dash to panel allows that, I will investigate it and see how they did it.

**Comment by rockon999** [comment]
Closing, out of scope of this plugin.
