### ISSUE TITLE
Text & icons are blurred in 3.26

### ISSUE THREAD

**Issue by gitjod** [rockon999/dynamic-panel-transparency#76]
I am on gnome 3.26
If I enable custom text coloring and have primary color selected as black, the text & icons in the top bar are blurred. Turning on the options for text & icon shadowing fix this but I don't like shadowing

![screenshot from 2017-09-18 18-11-06](https://user-images.githubusercontent.com/12417441/30554900-e33db2c2-9c9d-11e7-9a62-237d233d9a0e.png)

**Comment by rockon999** [comment]
@gitjod The reason this is happening is Gnome changed their default theme in 3.26. By default Adwaita (the default theme) in 3.26 has a slight shadow behind the text to make it more visible. This shadow isn't really noticeable on white text, but on black it creates that slightly blurry look. To disable the shadow you'll either have to enable shadowing in the extension and set everything to 0 or switch to a shell theme that doesn't have a text shadow effect.

**Comment by gitjod** [comment]
Thanks for the quick reply. I enabled shadowing in the extension and set everything to 0 and everything is back to the way is was in 3.24

**Comment by rockon999** [comment]
Closing, upstream issue.
