### ISSUE TITLE
Panel always be transparent when using plank(set on left or right)

### ISSUE THREAD

**Issue by IsoaSFlus** [rockon999/dynamic-panel-transparency#77]
GNOME version:3.24
system:Ubuntu GNOME 17.04 AMD64
btw:which is the best dock on GNOME?I can't stand the bad graphic performance of dash to dock!
Some screenshots:
![2017-09-21 12-55-30](https://user-images.githubusercontent.com/5125031/30679483-8f257fe0-9ecc-11e7-82aa-6a80a038901c.png)
![2017-09-21 12-55-35 的屏幕截图.png](https://i.loli.net/2017/09/21/59c3491f51c3c.png)

But the plank's setting window could trigger the transition.
![2017-09-21 12-55-53 的屏幕截图.png](https://ooo.0o0.ooo/2017/09/21/59c3492470853.png)

**Comment by rockon999** [comment]
Are you reporting a bug or requesting a feature?

**Comment by IsoaSFlus** [comment]
@rockon999 oh,I'm sorry.I mean it's a bug.When I use plank setting a dock on left or right of screen, panel won't trigger any transition(transparent all the time).

**Comment by rockon999** [comment]
@IsoaSFlus I can reproduce, I'll publish a fix in the next few days.

**Comment by rockon999** [comment]
Fix awaiting approval on Gnome Extensions. Closing.
