### ISSUE TITLE
panel goes dark when a window is close

### ISSUE THREAD

**Issue by TurboGit** [rockon999/dynamic-panel-transparency#79]
Before last update my panel was transparent and became black when a window was maximized.

Now as soon as a window (Emacs, Nautilus, Gedit...) is close to the panel (something like 10 pixels maybe) the panel becomes black. I didn't found a setting for this new behavior. Is that expected?

Thanks.

**Comment by rockon999** [comment]
It shouldn't be ~10 pixels, but the behavior is expected, yes. I made the change to support more applications and use cases. I'll work on making it less apparent (if it looks like ~10 pixels that is too much and a bug). Out of curiosity is your monitor HiDPI (2k, 4k, etc.)?

**Comment by rockon999** [comment]
@TurboGit I've added a toggle to this behaviour in the latest version (v24) on the GitHub. I'll be pushing it to Gnome Extensions today.

**Comment by TurboGit** [comment]
No not a 2k or 4k monitor, just a standard full HD (1920x1080).

Thanks for the additional control for this behavior. I think I'll stick to the previous behavior, only dark when a maximized window is present.

**Comment by rockon999** [comment]
Preference added to v24, awaiting approval on Gnome Extensions. Closing.

**Comment by TurboGit** [comment]
Thanks! Waiting for it too :)
