### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by ichundu** [rockon999/dynamic-panel-transparency#8]
Hello,
i cannot activate this extension in Gnome 3.18.2 on Arch Linux. The error is:
TypeError: Main.screenShield is null

Regards

**Comment by rockon999** [comment]
Hi! This issue actually just came up yesterday in another person's computer. The latest version from this repository will fix your issues. The version on Gnome Extensions will be updated within the next day or so.

**Comment by ichundu** [comment]
Thank you for the quick fix. issue solved :)
