### ISSUE TITLE
Preferences broken in Gnome Shell 3.26 (Ubuntu 17.10 Beta 2)

### ISSUE THREAD

**Issue by Austint30** [rockon999/dynamic-panel-transparency#81]
This is the error I get when I open the extension preferences using Gnome Tweaks. I am using Ubuntu 17.10 Beta 2

> Gio.IOErrorEnum: Error opening file /home/austin/.local/share/gnome-shell/extensions/dynamic-panel-transparency@rockon999.github.io/prefs.js: Is a directory
> 
> Stack trace:
>   Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
>   @<main>:1:43

**Comment by rockon999** [comment]
Hi! See #80 for a complete explanation of this issue. The fix is currently awaiting review on Gnome Extensions but v24 is available from the [releases page](https://github.com/rockon999/dynamic-panel-transparency/releases).
