### ISSUE TITLE
Advanced app tweaks broken under gnome 3.26.

### ISSUE THREAD

**Issue by Isaac-bankier** [rockon999/dynamic-panel-transparency#82]
Hi rockon there seems to be a bug in the preferences in the "app tweaks" section. Specifically the advanced button.
When pushed it will behave normal ( showing entry for the wm class ) but it will not allow you to edit or remove the entry. Additionally when the preferrences are closed the entry is removed. 

I'm running this on arch and using the git version that I downloaded today.

**Comment by rockon999** [comment]
I'll look into this tonight or tomorrow depending on my availability. 3.26 upgraded a lot of internal functionality (specifically GJS which runs the extension/preferences) and this upgrade modified quite a few features of the language. It is most likely that some line of code isn't quite right for 3.26 in that specific area of preferences.

**Comment by sandangel** [comment]
I'm looking for a fix too. It look like system trying to open prefs.js as a file, not a directory.

**Comment by rockon999** [comment]
@sandangel That issue should be fixed as of #80 and #81 @Isaac-bankier I just pushed a patch, this issue should be fixed in the latest master.
