### ISSUE TITLE
Install as system extension but sotre settings per user

### ISSUE THREAD

**Issue by chris968** [rockon999/dynamic-panel-transparency#84]
Hi,

There is a way to install the extension as a system extension (/usr/share/gnome-shell/extensions/) but store the settings into users home dir ?

**Comment by rockon999** [comment]
I have considered it, yes.  But for now the extension cannot be installed as a system extension as it stores data inside its directory. I'll see if I can't add this feature soon, though!

**Comment by rockon999** [comment]
This will be implemented in v26 or v27 depending on testing. I will be pushing these changes to the master branch in the coming days.

**Comment by rockon999** [comment]
This has been submitted to Gnome Extensions and will be a part of v26 and v27

**Comment by rockon999** [comment]
Implemented.
