### ISSUE TITLE
Panel background gets cut off/cropped

### ISSUE THREAD

**Issue by HackaN** [rockon999/dynamic-panel-transparency#85]
I noticed that the very bottom part, maybe the last pixel-row, gets removed when using the extension.
I took screenshots which showcases the difference. As you can see there's a black border missing when extension is active.

Without the extension: https://cloud.woelkli.com/s/Ckq150lZsJcDHQ6
With the extension: https://cloud.woelkli.com/s/a1qpSoH0nKIq5rJ

Dynamic Panel Transparency v24
Gnome v3.26.2
I am on Wayland, haven't tried it in X.

/hackan

**Comment by rockon999** [comment]
What shell theme is that?

**Comment by HackaN** [comment]
https://www.opendesktop.org/p/1195462/

**Comment by rockon999** [comment]
Could you try the latest version from the GitHub? I've tweaked some theme handling code and it should handle themes like Maxim better.

**Comment by HackaN** [comment]
Works Perfect 😄
Thank you!
sön 2017-11-05 klockan 02:15 +0000 skrev Evan Welsh:

**Comment by HackaN** [comment]
I updated to version 25 from extensions.gnome.org on my other Gnome-machine and the same issue was still there. I replaced the extension with the zip from here and now it works as it should.

**Comment by rockon999** [comment]
Gnome Extensions takes a few weeks to approve updates so v26 will contain this fix.
