### ISSUE TITLE
Failed to find shell theme settings

### ISSUE THREAD

**Issue by bryce-lynch** [rockon999/dynamic-panel-transparency#87]
Just wanted to report that in journalctl I see the following messages:

local gnome-shell[516]: [Dynamic Panel Transparency] Failed to find the user theme extension.
local gnome-shell[516]: [Dynamic Panel Transparency] Using theme data for: Adwaita
local gnome-shell[516]: [Dynamic Panel Transparency] Failed to find shell theme settings. Ignore this if you are not using a custom theme.

I'm using a custom gtk/shell theme combination, and the user theme extension is installed. I have also tried changing shell theme just to be sure.

**Comment by rockon999** [comment]
Hello!

Could you tell me...
- what Gnome Shell version you are using
- which theme you are using
- if this path exists in dconf org/gnome/shell/extensions/user-theme
- if so, a screenshot of the path would be great!

Thanks!

**Comment by bryce-lynch** [comment]
- GS version is 3.26.2 (latest ArchLinux package 3.26.2+9+ga3736d3a3-1)
- Numix-Frost as both the shell and the gtk theme (I also tried with Gnome-Pro but when I activate the extension I see the same message in journalctl)
- the user-theme key is "Numix-Frost", see https://i.imgur.com/XfWOWkD.jpg
