### ISSUE TITLE
Gnome Shell 3.26.2 (Arch x64) getting crashed

### ISSUE THREAD

**Issue by ajaybhatia** [rockon999/dynamic-panel-transparency#88]
Whenever I tried to open Chromium the shell gets crashed with a delay. I messed a lot with system with resetting chromium, resetting dconf etc but at last I tried to disable all installed extensions one by one and find that this extension is a culprit.

Issue needs to be resolved

**Comment by rockon999** [comment]
I've reproduced. Working on it :)

**Comment by rockon999** [comment]
I tried to fix this for 3.26 but it was something under the hood. It doesn't appear to happen in 3.28 and 3.30 so I'm closing as I believe the fixes have been backported.
