### ISSUE TITLE
An error loading the extension

### ISSUE THREAD

**Issue by noisnogit** [rockon999/dynamic-panel-transparency#9]
Good evening.
I am having this error on the last version:
"No signal 'unminimize' on object 'ShellWM'"

Running Debian 8 (jessie) - Gnome version 3.14.1

Thank you

**Comment by rockon999** [comment]
Hi! It appears Gnome 3.14 lacks some code this extension needs to function properly. Give me a few days and I'll see if I can't figure out a workaround!

**Comment by noisnogit** [comment]
Thanks for your prompt response :) 

If it helps, the previous version was running smoothly...

**Comment by rockon999** [comment]
Hi! The latest version on the GitHub should fix the problem. If you could test it out for me that'd be amazing! I'll try to get it up on Gnome Extensions within a few days.

**Comment by noisnogit** [comment]
Everything went back to work perfectly. Even all options. The gnome-shell is not accusing any errors ;)

Thank you very much.

Give me a hint if you have anything I can do to help...

**Comment by noisnogit** [comment]
Hello again.
The latest version of the extension fixed the problem and the gnome-shell stopped to acknowledge any error, but in the last reboot of my machine the extension stopped loading again. But this time due to another error: 

"ReferenceError: Util is not defined"

I was doubtful about opening a new issue, so I decided to reopen this one...

**Comment by rockon999** [comment]
Should be all good now!

**Comment by noisnogit** [comment]
Solved. Thank you...

**Comment by noisnogit** [comment]
Hi. 
With the last release the extension stopped loading again due to a reference error:

"ReferenceError: is_undef is not defined"

**Comment by rockon999** [comment]
Hi! This issue has been fixed and the current update has been recalled on Gnome Extensions. You'll receive an update to the fixed version as soon as the Gnome Extensions review team approves it. Please make sure to file a new issue report in the future or I may not get notifications about your problem!

**Comment by noisnogit** [comment]
Sorry for the late response. The last modifications appear to solve the problem. Thank you for the quick fix =D

In the next time I will open a new issue...
