### ISSUE TITLE
Dock not staying transparent

### ISSUE THREAD

**Issue by a-ridley** [rockon999/dynamic-panel-transparency#90]
Dock is not transparent while topbar is. At one point dock was transparent but then when I maximized my window dock turned black. Both maximized and unmaximized opacity are set to 0%. I'm on GNOME 3.28. 
![screenshot from 2018-05-21 02-27-11](https://user-images.githubusercontent.com/18725916/40300605-94311afe-5c9e-11e8-9418-c0eacb5238f4.png)

**Comment by rockon999** [comment]
This extension doesn't control the dock.
