### ISSUE TITLE
DPT not working in Gnome 3.30 anymore

### ISSUE THREAD

**Issue by pycebs** [rockon999/dynamic-panel-transparency#91]
I just updated to Gnome 3.30 and I cannot activate the DPT extension anymore. This is also happening with a few other extensions that haven't gotten an upgrade for 3.30 yet.

**Comment by daniel88ferreira** [comment]
The error it gives:
~~~bash
Extension "dynamic-panel-transparency@rockon999.github.io" had error: SyntaxError: redeclaration of const GdkPixbuf
~~~

**Comment by Smarthard** [comment]
This PRs might be useful:
https://github.com/eonpatapon/gnome-shell-extension-caffeine/pull/124
https://github.com/micheleg/dash-to-dock/pull/770

**Comment by rockon999** [comment]
@Smarthard @daniel88ferreira @pycebs I've fixed the master branch. Let me know if it works for you, I'll push to Gnome Extension after some testing.

**Comment by Smarthard** [comment]
@rockon999 yep. It's works fine now. Thank you!

**Comment by daniel88ferreira** [comment]
@rockon999 it's works nice like before. thanks! :)

**Comment by pycebs** [comment]
@rockon999 I downloaded the current git master and it works now, but there's still a small issue. 
My system language is German so I don't know what the English term for it is, but in the settings options you have: Transition? - Foreground - Background - App optimizations??

And if you go into app-optimizations I always add the drop-down-terminal extension so the top-bar goes dark when the drop-down-terminal comes down. 

However I cannot add any applications. I can select them and then choose "Select", but the entry is not actually added. I tried to add different other apps as well and it doesn't work either.

Can you or anyone else confirm that error?

**Comment by rockon999** [comment]
@pycebs it's another 3.30 bug I'm working on fixing.

**Comment by rockon999** [comment]
@pycebs I've pushed my preliminary work on fixing this issue to master, let me know if that fixes the bug!

**Comment by pycebs** [comment]
@rockon999 I just pulled it and it fully works again now. Nice job!

**Comment by arthurflor** [comment]
Hey, it works! (Arch Gnome 3.30.2)
Thanks!

**Comment by rockon999** [comment]
Should be running fine on 3.30 and the extension update is in review on extensions.gnome.org (though reviews are taking months at this point, so who knows how long that will take)
