### ISSUE TITLE
gnome-tweak doesn't show this extension

### ISSUE THREAD

**Issue by vthuongt** [rockon999/dynamic-panel-transparency#93]
Hi,
this extension seems to work for since I can see that the transparency changes when i maximize a window. However the dynamic panel transparency extension is not shown in the extension tab of the gnome-tweak-tool whereas other extensions are displayed correctly. Thus I can't access the settings or deactivate the extension. How can I fix this?

OS: Ubuntu 18.04
Gnome: 3.28.3

PS.: I installed this extension via git clone and then copied the folder to ~/.local/share/gnome-shell/extensions

**Comment by GuenMat** [comment]
Hi, I had a similar issue.

You need to copy only the folder named "dynamic-panel-transparency@rockon999.github.io" from the git clone in the folder : ~/.local/share/gnome-shell/extensions/
Then reload your shell using Alt+F2 r Enter.
And finally run in the command line :1st_place_medal:  gnome-shell-extension-tool -e dynamic-panel-transparency@rockon999.github.io

**Comment by vthuongt** [comment]
Issues was solved by this helpful answer.
> 
> 
> Hi, I had a similar issue.
> 
> You need to copy only the folder named "[dynamic-panel-transparency@rockon999.github.io](mailto:dynamic-panel-transparency@rockon999.github.io)" from the git clone in the folder : ~/.local/share/gnome-shell/extensions/
> Then reload your shell using Alt+F2 r Enter.
> And finally run in the command line : gnome-shell-extension-tool -e [dynamic-panel-transparency@rockon999.github.io](mailto:dynamic-panel-transparency@rockon999.github.io)
